# Generated by Django 4.0 on 2021-12-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Foods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('source', models.TextField(default='')),
                ('user', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='NE_Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.IntegerField()),
                ('food_cap', models.IntegerField()),
                ('water_cap', models.IntegerField()),
                ('poop', models.IntegerField()),
                ('poop_state', models.TextField()),
                ('pee', models.IntegerField()),
                ('pee_state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Poop_opt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
    ]
