# Generated by Django 4.0 on 2021-12-17 09:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foods',
            name='fullname',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ne_record',
            name='edit_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ne_record',
            name='update_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='foods',
            name='name',
            field=models.TextField(default=''),
        ),
    ]
