# Generated by Django 4.0 on 2021-12-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_pee_opt_rename_foods_foods_opt_ne_record_pee_cap'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ne_record',
            old_name='food_name',
            new_name='food',
        ),
    ]
