# Generated by Django 4.0 on 2021-12-19 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_food_name_ne_record_food'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ne_record',
            old_name='food',
            new_name='food_opt',
        ),
        migrations.RenameField(
            model_name='ne_record',
            old_name='pee',
            new_name='pee_opt',
        ),
        migrations.RenameField(
            model_name='ne_record',
            old_name='poop',
            new_name='poop_opt',
        ),
    ]
