# Generated by Django 4.0 on 2021-12-19 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_ne_record_edit_date_ne_record_insert_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ne_record',
            name='insert_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ne_record',
            name='update_date',
            field=models.DateTimeField(default=None),
        ),
    ]
