# Generated by Django 4.0 on 2021-12-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_foods_fullname_ne_record_edit_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ne_record',
            name='food_state',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ne_record',
            name='user_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ne_record',
            name='pee_state',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ne_record',
            name='poop_state',
            field=models.TextField(default=''),
        ),
    ]
