# Generated by Django 4.0 on 2021-12-19 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_food_ne_record_food_opt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ne_record',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ne_record',
            name='food_cap',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ne_record',
            name='food_opt',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ne_record',
            name='pee_cap',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ne_record',
            name='pee_opt',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ne_record',
            name='poop_opt',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ne_record',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ne_record',
            name='water_cap',
            field=models.IntegerField(default=-1),
        ),
    ]
