# Generated by Django 4.0 on 2021-12-19 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_ne_record_edit_date_alter_ne_record_food_cap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ne_record',
            name='edit_date',
        ),
        migrations.AddField(
            model_name='ne_record',
            name='insert_date',
            field=models.DateTimeField(default=None),
        ),
    ]
